const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const {test}=require('node:test');
const original=readFileSync('index-HdJXluQP.js','utf8');
const helpers=original.slice(original.indexOf('const Aw='),original.indexOf('const em='));
const source=readFileSync('payments.js','utf8');
const payment=(extra={})=>({date:'2026-10-07',client:'Ejemplo',concept:'Señal',category:'Bodas',amount_cents:20000,payment_kind:'client_payment',job_id:'job1',payment_method:'Transferencia',payment_notes:'',...extra});
function setup() {
  let docs=new Map([['clients/job1',{name:'Boda',paid_cents:30000,total_cents:130000,updated_at:'v1'}],['clients/job2',{name:'Fallas',paid_cents:0,total_cents:90000,updated_at:'v1'}]]),tick=1;
  const context={Map,Set,Number,String,Date,Intl,FormData,URL,Blob,console,navigator:{onLine:true},Vp:{},nu:{currentUser:{uid:'owner'}},tB:table=>table,vm:(table,id='new')=>({path:table+'/'+id,id}),Hf:t=>t,Yg:()=>`v${++tick}`,vw:()=>Error('conflicto'),uF:async()=>{},cF:async()=>{}};
  context._w=async(_,fn)=>{
    const pending=new Map([...docs].map(([k,v])=>[k,structuredClone(v)]));let writing=false;
    await fn({get:async ref=>{assert.equal(writing,false,'all reads must precede writes');const d=pending.get(ref.path);return{exists:()=>!!d,data:()=>d};},update:(ref,data)=>{writing=true;if(!pending.has(ref.path))throw Error('missing');pending.set(ref.path,{...pending.get(ref.path),...data});},set:(ref,data)=>{writing=true;pending.set(ref.path,data);},delete:ref=>{writing=true;pending.delete(ref.path);}});
    docs=pending;
  };
  const api=vm.runInNewContext(helpers+'\n'+source+'\n;({PaymentServices,paymentPayload,paymentCSV,uF,cF})',context);
  return{...api,get:key=>docs.get(key),entry:id=>({...docs.get('income/'+id),id}),put:(key,data)=>docs.set(key,data),income:()=>[...docs].filter(([k])=>k.startsWith('income/')).map(([,v])=>v),context};
}
test('linked deposit creates one income and preserves previous receipts',async()=>{const s=setup();await s.PaymentServices.save(payment(),null,'p');assert.equal(s.income().length,1);assert.equal(s.get('clients/job1').paid_cents,50000);assert.equal(s.get('clients/job1').payment_total_cents,20000);});
test('retry with same payment ID cannot count twice',async()=>{const s=setup();await s.PaymentServices.save(payment(),null,'p');await s.PaymentServices.save(payment(),null,'p');assert.equal(s.income().length,1);assert.equal(s.get('clients/job1').paid_cents,50000);});
test('unassigned payment can be linked later without a second income',async()=>{const s=setup();await s.PaymentServices.save(payment({job_id:''}),null,'p');assert.equal(s.get('clients/job1').paid_cents,30000);await s.PaymentServices.save(payment(),s.entry('p'),'p');assert.equal(s.income().length,1);assert.equal(s.get('clients/job1').paid_cents,50000);});
test('recover existing income without changing aggregate revenue',async()=>{const s=setup();const income={date:'2026-10-01',client:'Ejemplo',concept:'Señal',category:'Bodas',amount_cents:20000,created_at:'v1',updated_at:'v1'};s.put('income/existing',income);await s.PaymentServices.save(payment({job_id:''}),s.entry('existing'),'existing');assert.equal(s.income().length,1);assert.equal(s.income()[0].amount_cents,20000);assert.equal(s.income()[0].created_at,'v1');});
test('recover money already included in paid total, then edit by difference',async()=>{const s=setup();await s.PaymentServices.save(payment(),null,'p',true);assert.equal(s.get('clients/job1').paid_cents,30000);await s.PaymentServices.save(payment({amount_cents:25000}),s.entry('p'),'p');assert.equal(s.get('clients/job1').paid_cents,35000);assert.equal(s.get('clients/job1').payment_total_cents,25000);});
test('moving a payment changes both jobs in one transaction',async()=>{const s=setup();await s.PaymentServices.save(payment(),null,'p');await s.PaymentServices.save(payment({job_id:'job2'}),s.entry('p'),'p');assert.equal(s.get('clients/job1').paid_cents,30000);assert.equal(s.get('clients/job1').payment_total_cents,0);assert.equal(s.get('clients/job2').paid_cents,20000);});
test('unlinking leaves the income and restores the job balance',async()=>{const s=setup();await s.PaymentServices.save(payment(),null,'p');await s.PaymentServices.save(payment({job_id:''}),s.entry('p'),'p');assert.equal(s.get('clients/job1').paid_cents,30000);assert.equal(s.income().length,1);});
test('deleting linked income also reverses its contribution to the job',async()=>{const s=setup();await s.PaymentServices.save(payment(),null,'p');await s.cF('income',s.entry('p'));assert.equal(s.income().length,0);assert.equal(s.get('clients/job1').paid_cents,30000);});
test('overpayment fails atomically, preserving income and both jobs',async()=>{const s=setup();await s.PaymentServices.save(payment(),null,'p');await assert.rejects(s.PaymentServices.save(payment({job_id:'job2',amount_cents:100000}),s.entry('p'),'p'),/supera/);assert.equal(s.get('clients/job1').paid_cents,50000);assert.equal(s.get('clients/job2').paid_cents,0);assert.equal(s.get('income/p').amount_cents,20000);});
test('stale forms fail without overwriting another edit',async()=>{const s=setup();await s.PaymentServices.save(payment(),null,'p');const stale=s.entry('p');await s.PaymentServices.save(payment({amount_cents:25000}),s.entry('p'),'p');await assert.rejects(s.PaymentServices.save(payment({amount_cents:30000}),stale,'p'),/conflicto/);assert.equal(s.get('clients/job1').paid_cents,55000);});
test('legacy recovery cannot reuse money already detailed in other payments',async()=>{const s=setup();await s.PaymentServices.save(payment(),null,'p',true);await assert.rejects(s.PaymentServices.save(payment(),null,'q',true),/anteriormente/);assert.equal(s.income().length,1);});
test('manual job editing and deletion cannot invalidate linked receipts',async()=>{const s=setup();await s.PaymentServices.save(payment(),null,'p');await assert.rejects(s.uF('clients',{paid_cents:10000},s.get('clients/job1')),/menor/);await assert.rejects(s.cF('clients',s.get('clients/job1')),/vinculados/);});
test('unknown jobs and offline saves do not write partial income',async()=>{const s=setup();await assert.rejects(s.PaymentServices.save(payment({job_id:'missing'}),null,'p'),/no existe/);assert.equal(s.income().length,0);s.context.navigator.onLine=false;await assert.rejects(s.PaymentServices.save(payment(),null,'p'),/conexión/);});
test('money parser rejects zero, invalid dates and more than two decimals',()=>{const s=setup();const form=new Map(Object.entries({...payment(),amount_cents:'200,50'}));assert.equal(s.paymentPayload(form).amount_cents,20050);form.set('amount_cents','0');assert.throws(()=>s.paymentPayload(form),/mayor/);form.set('amount_cents','1,001');assert.throws(()=>s.paymentPayload(form),/decimales/);form.set('amount_cents','1');form.set('date','2026-02-30');assert.throws(()=>s.paymentPayload(form),/fecha/);});
test('CSV export protects spreadsheet formulas and preserves exact cents',()=>{const s=setup();const csv=s.paymentCSV([payment({client:'=1+1',amount_cents:12345})],[]);assert.ok(csv.includes("\"'=1+1\""));assert.ok(csv.includes('"123,45"'));});
